name: lapin
adopt-info: lapin
summary: lapin
base: core18
description: |
  A game I built under direction of my kids
  Move a rabbit trying to reach grass withhout being eaten or fired at.

confinement: strict

parts:
  lapin:
    source: https://github.com/Canop/lapin.git
    plugin: rust
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git rev-parse --short HEAD)"

apps:
  lapin:
    command: lapin

